#!/bin/bash
#
# Copyright @ cheneydc 
# Date  : 2015-12-02
# Author: cheneydc
# Email : <cheneydc@gmail.com>
#
# Distributed under terms of the MIT license.

# Define env
export NOVA_PROXY_ADMIN_USER=""
export NOVA_PROXY_ADMIN_PASS=""
export NOVA_PROXY_ADMIN_TENANT_NAME=""
export TROVE_AUTH_URL=""
export RABBIT_HOST=""
export RABBIT_PASSWD=""
export RABBIT_USERID=""
export RABBIT_VIRTUAL_HOST=""

export HOST_USERNAME=""
export HOST_SCP_USERNAME=""
export RELEASE=""
export PROJECT_BRANCH='stable/${RELEASE}'
export GUEST_USERNAME=""
export TROVE_USER="trove"
export RELEASE="trusty"
export NETWORK_GATEWAY=""
export SERVICE_TYPE=${DATABASE_TYPE}
export ESCAPED_PATH_TROVE=""
export SSH_DIR=""
export ESCAPED_GUEST_LOGDIR=""
export PATH_TRIPLEO_ELEMENTS=${TRIPLEO_CLONE_DIR}
export REDSTACK_SCRIPTS=${TROVE_CLONE_DIR}/scripts
export ELEMENTS_PATH=$REDSTACK_SCRIPTS/files/elements:$PATH_TRIPLEO_ELEMENTS/elements
export REQUIREMENTS_FILE=$REDSTACK_SCRIPTS/files/requirements/ubuntu-requirements-default.txt
export DIB_CLOUD_INIT_DATASOURCES="ConfigDrive"
