#!/bin/bash
#
# Copyright @ cheneydc 
# Date  : 2015-12-02
# Author: cheneydc
# Email : <cheneydc@gmail.com>
#
# Distributed under terms of the MIT license.

# Define env
export NOVA_PROXY_ADMIN_USER="admin"
export NOVA_PROXY_ADMIN_PASS="Neunn@123"
export NOVA_PROXY_ADMIN_TENANT_NAME="admin"
export TROVE_AUTH_URL="http:\/\/192.168.250.7:35357\/v2.0"
export RABBIT_HOST="192.168.250.31"
export RABBIT_PASSWD="openstack"
export RABBIT_USERID="openstack"
export RABBIT_VIRTUAL_HOST="\/"

export HOST_USERNAME="ubuntu"
export HOST_SCP_USERNAME="ubuntu"
export RELEASE="liberty"
export PROJECT_BRANCH='stable/${RELEASE}'
export GUEST_USERNAME="ubuntu"
export TROVE_USER="trove"
export RELEASE="trusty"
export NETWORK_GATEWAY="192.168.99.1"
export SERVICE_TYPE=${DATABASE_TYPE}
export ESCAPED_PATH_TROVE="\/opt\/stack\/trove"
export SSH_DIR="/home/ubuntu/.ssh"
export ESCAPED_GUEST_LOGDIR="\/opt\/stack\/logs"
export PATH_TRIPLEO_ELEMENTS=${TRIPLEO_CLONE_DIR}
export REDSTACK_SCRIPTS=${TROVE_CLONE_DIR}/scripts
export ELEMENTS_PATH=$REDSTACK_SCRIPTS/files/elements:$PATH_TRIPLEO_ELEMENTS/elements
export REQUIREMENTS_FILE=$REDSTACK_SCRIPTS/files/requirements/ubuntu-requirements-default.txt
export DIB_CLOUD_INIT_DATASOURCES="ConfigDrive"
