#!/bin/bash
# Fully upgrade everything on the system (if the package manager knows how to
# do it).

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5EDB1B62EC4926EA
apt-key update & apt-get update 

install-packages -u
